server {
    listen 80;

    location /orders/ {                                 #need to containerize the services for order and payment for nginx to 
        proxy_pass http://order-service:3001;            communicate with them
        proxy_set_header Host $host;                    -- gets host(references to where the client is trying to access)
        proxy_set_header X-Real-IP $remote_addr;        -- acquires the ip of client(can be used for rate limiting,etc)
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;    -- x-fwded-for is designed to preserve a chain of proxy Ips
        proxy_set_header X-Forwarded-Proto $scheme;         -- nginx might communicate with http but this gives real protocol used by client
    }

    location /payments/ {
        proxy_pass http://payment-service:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


